<%@ include file="/jsp/inc/definitions.inc" %>
<% 
   String[] tableNames = request.getParameterValues("tableNames");
   String tablename = (String)request.getParameter(PublicLabel.TABLENAME);
   if (tablename == null) {
       tablename = (String)request.getAttribute(PublicLabel.TABLENAME);
   }
   int numRows = (tablename == null)?20:15;
   //int whereRows = (tablename == null)?5:4;
   String display = (String)request.getParameter("display");  
   ArrayList scriptList = (ArrayList)request.getAttribute("column_names");
   //System.out.println(request.getParameter("tableInfoWindow"));
   
%>
<HTML>
<HEAD>
<meta http-equiv="pragma" content="no-cache">
<meta http-equiv="cache-control" content="no-cache">
<meta http-equiv="expires" content="0"> 
<link type="text/css" rel=stylesheet href="<%=contextPath%>/styles/basic.css">
<link type="text/css" rel=stylesheet href="<%=contextPath%>/styles/fk.css">
<link type="text/css" rel=stylesheet href="<%=contextPath%>/styles/dhtmlwindow.css">
<SCRIPT Language="JavaScript" SRC="<%=contextPath%>/scripts/common.js"></SCRIPT>
<SCRIPT Language="JavaScript" SRC="<%=contextPath%>/scripts/dhtmlwindow.js"></SCRIPT>
<SCRIPT LANGUAGE="JavaScript">
var count = 0;
var scripts = new Array();

function ScriptNameValue(name, value) {
   this.name = name;
   this.value = value;
}

function setScript(name, value) {
   scripts[count++] = new ScriptNameValue(name, value);
}

function changeSize() {
   //alert('changeSize');
   var selectedBox = document.getElementById("selected");
   var availableBox = document.getElementById("available");
   var orderbyBox = document.getElementById("orderby");
   var ieHeight = Math.max(190,(document.body.clientHeight-380));
   var ffHeight = Math.max(180,(window.innerHeight-350));
   if (window.innerWidth) { //if browser supports window.innerWidth
       selectedBox.style.height=ffHeight;
       availableBox.style.height=ffHeight;
       orderbyBox.style.height=ffHeight;
   } else if (document.all) { //else if browser supports document.all (IE 4+)
       selectedBox.style.height=ieHeight;
       availableBox.style.height=ieHeight;
       orderbyBox.style.height=ieHeight;
   }
}

<% if (scriptList != null) {
       for (Iterator scripts = scriptList.iterator(); scripts.hasNext();) {
            NameValuePair pair = (NameValuePair)scripts.next();
            //String script = (String)scripts.next();
%>
            setScript("<%=pair.getName()%>", "<%=pair.getValue()%>");
<%     }
   }
%>
</SCRIPT>
<TITLE><%=tablename%> - SQL Query Builder</TITLE>
</HEAD>

<body OnLoad="stopProcessing();initChoiceBox();changeSize();" onresize='changeSize();'>
<center>

<% if (Boolean.valueOf(display).booleanValue()) { 
       out.println(PublicAPI.menu(contextPath, tablename, "", connId, browser, db_name));
   } else {
	   out.println(PublicAPI.processingDiv(imagePath));
   }
   if (tablename != null) {
       out.println(PublicAPI.printTitle(display, tablename, "Table Query Builder"));
   } else {
%> 
<table style="border:0px;width:740px">
<tr>
<td align=left>
  <span class="mainTitle">SQL Query Builder</span>
  &nbsp;&nbsp;&nbsp;&nbsp;
  <span class="tableInfo">Database:</span>
  <span class="mainDB"><%=db_name%></span>
</td>
</tr>
</table>
<% } %>
<FORM NAME="choiceForm"
      METHOD="POST"
      ACTION="<%=actionPath%>/SQLWork"
      OnSubmit="return verifyQuery();">
<INPUT TYPE="hidden" NAME="connId" value="<%=connId%>">
<INPUT TYPE="hidden" NAME="tablename" VALUE="<%=tablename%>">
<INPUT TYPE="hidden" NAME="tablename_qb" VALUE="<%=tablename%>">
<INPUT TYPE="hidden" NAME="display" VALUE="<%=display%>">
<INPUT TYPE="hidden" NAME="statement">
<INPUT TYPE="hidden" NAME="processing_bar" VALUE="flase">
<INPUT TYPE="hidden" NAME="show_statement" value="true">
<INPUT TYPE="hidden" NAME="tableInfoWindow" value="<%=request.getParameter("tableInfoWindow")%>">
<INPUT TYPE="hidden" NAME="resultObjectName" value="QueryBuilderResultObject">
<INPUT TYPE=hidden name="display_rows" value="100">
<table border=0 CELLPADDING=0 CELLSPACING=0 HSPACE=0 VSPACE=0>
<tr><td VALIGN=BOTTOM>
<nobr>
<div id="navcontainer">
<ul id="navlist">
<li><a href="javascript:window.history.back();" title="Back to previous page">&nbsp;&nbsp;Back&nbsp;&nbsp;</a></li>
<li><a href="javascript:showJavaBean();" title="Generate Data Access Object (DAO) for the table or Data Transfer Objects for multiple tables.">&nbsp;&nbsp;JavaBean&nbsp;&nbsp;</a></li>
<li><a href="javascript:viewQuery();" title="Preview the SQL statement generated by this Query Builder">&nbsp;&nbsp;View SQL&nbsp;&nbsp;</a></li>
<li><a href="<%=jspPath%>/advanced_query_help.jsp" title="Help for Query Builder">&nbsp;&nbsp;Help&nbsp;&nbsp;</a></li>
<li><a href="javascript:clearAll();" title="Clear all the selections">&nbsp;&nbsp;Clear All&nbsp;&nbsp;</a></li>
<li style="margin:0px, padding:0px;"><%=PublicAPI.getMaxRowsList()%></li>
<li><a href="javascript:submitQuery();" style='color:#ffffff;background-color:#8080C0;' title="Back to previous page">&nbsp;&nbsp;Execute Query&nbsp;&nbsp;</a></li>
</ul>
</div> 
</nobr>
</td></tr>
<tr><td align=center>
<INPUT TYPE="TEXT" style="width:750px;font-size=9px;border:1px solid #888;" NAME="msg">
</td></tr>
</table>
<p>
<TABLE WIDTH=500 BORDER=0 CELLPADDING=0 CELLSPACING=0 HSPACE=0 VSPACE=0>
<tr>
<td align=left><nobr>&nbsp;<b><font FACE="Arial" color=darkgreen>SELECT</font></b></nobr></td>
<td>&nbsp;</td>
<td align=left><nobr>&nbsp;
<font FACE="Arial" color=#0000A0><b>Tables</b></font> 
   (<%=request.getAttribute("numOfTables")%>) 
   <font FACE="Arial" color=green><b>&amp;</b></font> 
   <font FACE="Arial" color=#0000A0><b>Columns</b></font> 
   (<%=request.getAttribute("totalColumns")%>)</nobr>
</td>
<td>&nbsp;</td>
<td align=left><nobr>&nbsp;<b><font FACE="Arial" color=darkgreen>ORDER BY</font></b>&nbsp;
</nobr></td>
</tr>
<tr>
<td align=center valign="top"> 
<select multiple id="selected" name="selected" size=<%=numRows%> style="width:220px;height:190px;font-size:9px;border:1px solid grey;" onChange="showColumnNames();" onClick="showColumnNames();uncheckRT();">
<option>------------------------------------- 
</select>
</td>
<td style="width:30px;padding:0px;text-align:center;">
<table border=0 CELLPADDING=1 CELLSPACING=1>
<tr><td>
<%=PublicAPI.button2("javascript:choose(document.choiceForm.available, document.choiceForm.selected);", "_self", "left_arrow", imagePath, "Add selected table column(s) to the SELECT (left) box")%>
</td></tr><tr><td>
<%=PublicAPI.button2("javascript:selectAll(document.choiceForm.available, document.choiceForm.selected);", "_self", "all_left_arrow", imagePath, "Add all table columns to the SELECT (left) box")%>
</td></tr><tr><td>
<%=PublicAPI.button2("javascript:removeBox(document.choiceForm.selected);", "_self", "right_arrow", imagePath, "Remove selected coloum(s) from the SELECT (left) box")%>
</td></tr><tr><td>
<%=PublicAPI.button2("javascript:removeAllBox(document.choiceForm.selected);", "_self", "all_right_arrow", imagePath, "Remove all coloums from the SELECT (left) box")%>
</td></tr><tr><td>
<%=PublicAPI.button2("javascript:MoveupBox(document.choiceForm.selected);", "_self", "up_arrow", imagePath, "Move selected column(s) in the SELECT (left) box up in the box")%>
</td></tr><tr><td>
<%=PublicAPI.button2("javascript:MovedownBox(document.choiceForm.selected);", "_self", "down_arrow", imagePath, "Move selected column(s) in the SELECT (left) box down in the box")%>
</td></tr>
</table>
</td>
<td align=center valign="top">
<select multiple id="available" name="available" size=<%=numRows%> style="width:240px;height:190px;font-size:9px;border:1px solid grey;" onChange="showColumnNames();" onClick="showColumnNames();uncheckSR();">
<option>---------------------------------------- 
</select>
</td>
<td width=30 valign=middle align=center>
<table border=0 CELLPADDING=1 CELLSPACING=1>
<tr><td>
<%=PublicAPI.button2("javascript:choose(document.choiceForm.available, document.choiceForm.orderby);", "_self", "r_right_arrow", imagePath, "Add selected table column(s) to the ORDER BY (right) box")%>
</td></tr><tr><td>
<%=PublicAPI.button2("javascript:selectAll(document.choiceForm.available, document.choiceForm.orderby);", "_self", "r_all_right_arrow", imagePath, "Add all table columns to the ORDER BY (right) box")%>
</td></tr><tr><td>
<%=PublicAPI.button2("javascript:removeBox(document.choiceForm.orderby);", "_self", "r_left_arrow", imagePath, "Remove selected coloum(s) from the ORDER BY (right) box")%>
</td></tr><tr><td>
<%=PublicAPI.button2("javascript:removeAllBox(document.choiceForm.orderby);", "_self", "r_all_left_arrow", imagePath, "Remove all coloums) from the ORDER BY (right) box")%>
</td></tr><tr><td>
<%=PublicAPI.button2("javascript:MoveupBox(document.choiceForm.orderby);", "_self", "r_up_arrow", imagePath, "Move selected column(s) in the ORDER BY (right) box up in the box")%>
</td></tr><tr><td>
<%=PublicAPI.button2("javascript:MovedownBox(document.choiceForm.orderby);", "_self", "r_down_arrow", imagePath, "Move selected column(s) in the ORDER BY (right) box down in the box")%>
</td></tr>
</table>
</td>
<td align=center valign="top">
<select multiple id="orderby" name="orderby" size=<%=numRows%> style="width:210px;height:195px;font-size:9px;border:1px solid grey;" onChange="showColumnNames();" onClick="showColumnNames();uncheckST();">
<option>------------------------------------- 
</select>
</td>
</tr>
<!-- <tr><td colspan=5>

<nobr>&nbsp;<IMG SRC="<%=jspPath%>bullet.gif" WIDTH="10" HEIGHT="10" BORDER=0 ALT="">&nbsp;
<font color=#0000A0 size=-1>Hold down Ctrl or Shift key to select multiple columns.</font></nobr>
<img src=images/qb_down_arrow.gif border=0>
</td></tr> -->
<tr>
<% if (tablename == null) { %>
   <td valign=bottom><nobr><font FACE="Arial" color=darkgreen><B>FROM</B></font></nobr></td>
<% } else { %>
   <td valign=bottom><nobr><font FACE="Arial" color=darkgreen><B>WHERE</B></font></nobr></td>
<% } %>
<td colspan=3 align=center height=45>
<% if (tablename == null) { %>
   <%=PublicAPI.button2("javascript:getTableNames();", "_self", "to_from_box", imagePath, "Add selected table name(s) to the FROM box")%>
<% } %> 
<%=PublicAPI.button2("javascript:getColumnNames();", "_self", "to_where_clause", imagePath, "Add selected table column(s) to the WHERE clause box.")%>
<% if (tablename == null) { %>
   <%=PublicAPI.button2("javascript:joinTables();", "_self", "join_tables", imagePath, "Select two table columns to join the tables")%>
<% } %>
</td>
<td align=right valign=bottom>
<% if (browser != null && (browser.indexOf("MSIE") == -1)) { %>&nbsp;<% } %>
<% if (tablename == null) { %>
   <%=PublicAPI.button2("javascript:clearFrom();", "_self", "clear_from", imagePath, "Clear the FROM box")%>
<% } else { %>
   <%=PublicAPI.button2("javascript:clearWhere();", "_self", "clear_where", imagePath, "Clear the WHERE clause box")%>
<% } %>
</td>
</tr>
<% if (tablename == null) { %>
   <tr><td align=center colspan=5>
   <TEXTAREA style="width:740px;height:32px;border:1px solid grey;" NAME="from" WRAP="SOFT"><%=request.getAttribute("fromPart")%></TEXTAREA>
   </td></tr>
   <tr>
   <td valign=bottom><nobr><font FACE="Arial" color=darkgreen><B>WHERE</B></font></nobr></td>
   <td colspan=4 align=right>
   <%=PublicAPI.button2("javascript:clearWhere();", "_self", "clear_where", imagePath, "Clear the WHERE clause box")%>
   </td>
<% } %>
<tr><td align=center colspan=5>
 <TEXTAREA style="width:750px;height:50px;border:1px solid grey;" NAME="where" WRAP="SOFT"></TEXTAREA>
</td></tr>

<tr><td align=center colspan=5><nobr>
<div id="sqlcontainer">
<ul id="navlist">
<li><a href="javascript:append(' = ');" title="Equal">=</a></li>
<li><a href="javascript:append(' \' ');" title="Single quote">'</a></li>
<li><a href="javascript:append(' < ');" title="Less than">&lt;</a></li>
<li><a href="javascript:append(' <= ');" title="Less than or equal">&lt;=</a></li>
<li><a href="javascript:append(' > ');" title="Greater than">&gt;</a></li>
<li><a href="javascript:append(' >= ');" title="Greater than or equal">&gt;=</a></li>
<li><a href="javascript:append(' + ');" title="Plus">+</a></li>
<li><a href="javascript:append(' - ');" title="Minus">-</a></li>
<li><a href="javascript:append(' * ');" title="Star">*</a></li>
<li><a href="javascript:append(' / ');" title="Slash">/</a></li>
<li><a href="javascript:append(' % ');" title="Percent sign">%</a></li>
<li><a href="javascript:append(' _ ');" title="Underscore">_</a></li>
<li><a href="javascript:append(' (');" title="Left parenthesis">(</a></li>
<li><a href="javascript:append(') ');" title="Right parenthesis">)</a></li>
<li><a href="javascript:append(' <> ');" title="Not equal">&lt;&gt;</a></li>
<li><a href="javascript:append(' != ');" title="Not equal">!=</a></li>
<li><a href="javascript:append(' AND ');" title="And">and</a></li>
<li><a href="javascript:append(' OR ');" title="Or">or</a></li>
<li><a href="javascript:append(' IN ');" title="In">in</a></li>
<li><a href="javascript:append(' NOT IN ');" title="Not in">not in</a></li>
<li><a href="javascript:append(' LIKE ');" title="Like">like</a></li>
<li><a href="javascript:append(' EXISTS ');" title="Exists">exists</a></li>
<li><a href="javascript:append(' BETWEEN ');" title="Between">between</a></li>
<li><a href="javascript:append(' IS NULL ');" title="Is null">is null</a></li>
<li><a href="javascript:append(' IS NOT NULL ');" title="Is not null">is not null</a></li>
</ul>
</div> 
</nobr>
</td></tr>
</table>

</form>
<p>
<table style="border:0px;padding:0px;margin:0px;width:740px">
<tr>
<td><%=PublicAPI.copyrightStr()%></td>
<td align=right><%=PublicAPI.button("javascript:printPage();", "_self", "printpage", imagePath)%></td>
</tr></table>
</center>
<%=PublicAPI.getAQScripts(contextPath, browser, display)%>  
<SCRIPT LANGUAGE="JavaScript">
var aqIndex = getCookie("aqIndex")?getCookie("aqIndex"):"7";
document.choiceForm.display_rows.selectedIndex = aqIndex;
</SCRIPT>
</body>
</html>