select EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,JOB_ID, SALARY,MANAGER_ID,DEPARTMENT_ID from HR.EMPLOYEES;

select DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID from HR.DEPARTMENTS;

select JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY from HR.JOBS;

select LOCATION_ID,STREET_ADDRESS,POSTAL_CODE,CITY,STATE_PROVINCE, COUNTRY_ID from HR.LOCATIONS;